name: 575_jleg_rag_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - spacy
  - pip
  - pip:
    - langchain-community
    - langchain-core
    - sentence-transformers
    - faiss-cpu
    - streamlit
    - nltk
    - duckdb
    - langchain-huggingface
    - datasets
  - jupyterlab
  - ipykernel
  - ipywidgets
  - python-dotenv