name: 575_jleg_rag_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - pyarrow
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - spacy
  - pip
  - pip:
    - langchain-community
    - langchain-core
    - rank_bm25
  - jupyterlab
  - ipykernel
  - ipywidgets
  - python-dotenv